### ISSUE TITLE
Problems in Sketch 52.6

### ISSUE THREAD

**Issue by brunogdesign** [oodesign/icon-tools#4]
Hi,

Let me start by thanking you for this awesome plugin that I've been using since the first release.

I've found a bug in Sketch 52.6 (I haven't upgraded yet to 53 so I don't know if this is also happening there). When doing the "Prepare icons for export command" with the last release the end result is just one icon and it is exported wrongly, as a symbol. I've tried in multiple files (some old ones where I've used the plugin successfully in the past) and I got the same result every single time... 

<img width="402" alt="screenshot_2019-02-21_at_17_21_18" src="https://user-images.githubusercontent.com/1450050/53188557-8ec84b80-35fd-11e9-950c-bdd43a19c2f8.png">

I've then downloaded a previous release from this Github (v1.0.6 or v1.0.5) and everything went fine (as expected) on all those files so it's clearly a bug on the last release.

Let me know if I can help you solve the issue!

[test.sketch.zip](https://github.com/oodesign/icon-tools/files/2890368/test.sketch.zip)

Best regards,
Bruno

**Comment by oodesign** [comment]
Hi @brunogdesign,

Sorry to hear that. Some things changed in Sketch 53, and our latest release (v1.0.9) aimed to reach compatibility with Sketch 53+. Though... it seems we lost something in the trip.

We just released v1.0.10, which hopefully will restore compatibility with Sketch 48+.
Please, give it a try, and let us know how it worked for you!

Thanks!

**Comment by brunogdesign** [comment]
@oodesign thank you so much for solving this issue in such a small time frame ;)

Everything is working fine again! 

Best regards,
Bruno
